# Generated by Django 4.0.6 on 2022-07-19 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Please use at least 3 consecutive alphabetic characters', max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z][a-zA-Z]', message='wrong input')])),
                ('title', models.CharField(help_text='Please use at least 3 consecutive alphabetic characters', max_length=60, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z][a-zA-Z]', message='wrong input')])),
                ('text', models.TextField(max_length=3000)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
