# Generated by Django 4.0.6 on 2022-07-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
    ]
